/**
 * Central icon map. UI code imports from here rather than reaching into
 * `lucide-react` directly, so the icon vocabulary stays consistent and swappable.
 *
 * Accessibility: Lucide icons render an SVG with `aria-hidden` by default when used
 * decoratively. For meaningful, icon-only controls, wrap with an accessible label
 * (e.g. the `IconButton`/`Button` `aria-label`), never rely on the glyph alone.
 */
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BookOpen,
  Bookmark,
  Blocks,
  Box,
  Boxes,
  Braces,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Circle,
  Clock,
  Command,
  Database,
  Download,
  Copy,
  FileCode2,
  Flame,
  Gem,
  GitBranch,
  GitCompare,
  GraduationCap,
  Lock,
  Mail,
  Menu,
  MessageSquare,
  MoreHorizontal,
  Network,
  Pencil,
  Pause,
  Play,
  Plus,
  Pin,
  RotateCcw,
  Route,
  ScrollText,
  Search,
  Server,
  Star,
  ShieldCheck,
  SlidersHorizontal,
  Terminal,
  Trash2,
  Trophy,
  UserRound,
  Users,
  XCircle,
  X,
  Zap,
} from "lucide-react";

export const icons = {
  terminal: Terminal,
  yaml: FileCode2,
  docs: BookOpen,
  playground: Blocks,
  problems: AlertTriangle,
  cluster: Network,
  node: Server,
  pod: Box,
  deployment: Boxes,
  service: Route,
  endpointSlice: GitBranch,
  github: GitBranch,
  mail: Mail,
  events: Activity,
  logs: ScrollText,
  command: Command,
  search: Search,
  success: CheckCircle2,
  warning: AlertTriangle,
  error: XCircle,
  run: Play,
  pause: Pause,
  reset: RotateCcw,
  diff: GitCompare,
  validate: ShieldCheck,
  trophy: Trophy,
  streak: Flame,
  xp: Gem,
  database: Database,
  config: Braces,
  docsInteractive: GraduationCap,
  lock: Lock,
  bookmark: Bookmark,
  clock: Clock,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circle: Circle,
  arrowRight: ArrowRight,
  filter: SlidersHorizontal,
  challenge: Zap,
  community: Users,
  user: UserRound,
  close: X,
  edit: Pencil,
  trash: Trash2,
  menu: Menu,
  discussion: MessageSquare,
  download: Download,
  copy: Copy,
  more: MoreHorizontal,
  plus: Plus,
  pin: Pin,
  star: Star,
} as const;

export type IconName = keyof typeof icons;

export { ClusterMark } from "./cluster-mark";
